### ISSUE TITLE
[BUG] World.hop() causes script crash

### ISSUE THREAD

**Issue by iDznPB** [powbot/issues#136]
**Describe the bug**
Attempting to hop worlds causes script to  crash. Tried directly referencing the world, also tried streaming the world but no joy.

**To Reproduce/Line of code causing issue**

OR

```
                World world = Worlds.stream().id(302).first();
		System.out.println("Valid: "+world.valid() + " - World: "+world.getNumber());
		world.hop();
// also tried
                World world = new World(521, World.getNil().getPopulation(), World.getNil().textColor(), World.getNil().type(), World.getNil().server(), World.getNil().specialty());
		System.out.println("Valid: "+world.valid() + " - World: "+world.getNumber());
		world.hop();
// both print out a valid world but give the below error when trying to hop.
```

**Expected behavior**
Hop worlds

**Logs**
```
[SEVERE] script poll failed (TestScript99)
[SEVERE] java.util.NoSuchElementException: Collection contains no element matching the predicate.
	at org.powbot.mobile.SettingsManager.get(SettingsManager.kt:90)
	at org.powbot.mobile.SettingsManager.enabled(SettingsManager.kt:80)
	at org.powbot.api.rt4.World.false(World.kt:203)
	at org.powbot.api.rt4.World.hop(World.kt:237)
	at Tests.Test.poll(Test.java:92)
	at org.powbot.mobile.script.ScriptManager$runScript$4.invokeSuspend(ScriptManager.kt:364)
	at org.powbot.mobile.script.ScriptManager$runScript$4.invoke(Unknown Source:8)
	at org.powbot.mobile.script.ScriptManager$runScript$4.invoke(Unknown Source:4)
	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturnIgnoreTimeout(Undispatched.kt:100)
	at kotlinx.coroutines.TimeoutKt.setupTimeout(Timeout.kt:148)
	at kotlinx.coroutines.TimeoutKt.withTimeout(Timeout.kt:44)
	at org.powbot.mobile.script.ScriptManager.runScript(ScriptManager.kt:362)
	at org.powbot.mobile.script.ScriptManager.access$runScript(ScriptManager.kt:27)
	at org.powbot.mobile.script.ScriptManager$start$2.invokeSuspend(ScriptManager.kt:165)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
```

**Comment by constt** [comment]
Oops this was a result of testing do action hopping, fixed in 20

**Comment by iDznPB** [comment]
Working now, thank you!
