### ISSUE TITLE
[BUG] PowClient (overlay) not loading 

### ISSUE THREAD

**Issue by Krulvis** [powbot/issues#172]
**Describe the bug**
After the recent update I downloaded installer and installed latest version just now (28/11/2022 12:10 GMT) and the install went successful. However, after starting the OSRS app on my phone the powbot overlay does not show. I am unsure if its unable to download powbot client or if there's something else going wrong. I cleared cache and restarted to no avail.

**To Reproduce/Line of code causing issue**
1. Download powbot-installer
2. Install powbot on phone (OnePlus Nord 5G)
4. Open powbot on phone
5. Become sad :C

**Logs**
Like I said, I have no idea if these logs are useful but these are what I found during and after opening the osrs app on phone that could be related:
```
11-28 13:23:12.555  8742  8742 I TetheringManager: registerTetheringEventCallback:com.jagex.oldscape.android
11-28 13:23:12.557  8742  8742 E ldscape.androi: No implementation found for void com.jagex.android.ApplicationContext.onUpdateInternetAvailable(boolean, boolean) (tried Java_com_jagex_android_ApplicationContext_onUpdateInternetAvailable and Java_com_jagex_android_ApplicationContext_onUpdateInternetAvailable__ZZ)
11-28 13:23:12.561  8742  8742 E NXT_LOGGER: attempted to call onUpdateInternetAvailable but its not yet available - network state may be incorrect
11-28 13:23:12.561  8742  8742 E NXT_LOGGER: java.lang.UnsatisfiedLinkError: No implementation found for void com.jagex.android.ApplicationContext.onUpdateInternetAvailable(boolean, boolean) (tried Java_com_jagex_android_ApplicationContext_onUpdateInternetAvailable and Java_com_jagex_android_ApplicationContext_onUpdateInternetAvailable__ZZ)
11-28 13:23:12.561  8742  8742 E NXT_LOGGER:    at com.jagex.android.ApplicationContext.onUpdateInternetAvailable(Native Method)
11-28 13:23:12.561  8742  8742 E NXT_LOGGER:    at com.jagex.android.ApplicationContext.a(Unknown Source:73)
11-28 13:23:12.561  8742  8742 E NXT_LOGGER:    at com.jagex.android.ApplicationContext.c(Unknown Source:38)
11-28 13:23:12.561  8742  8742 E NXT_LOGGER:    at com.jagex.android.ApplicationContext.d(Unknown Source:8)
11-28 13:23:12.561  8742  8742 E NXT_LOGGER:    at com.jagex.android.ApplicationContext.<init>(Unknown Source:66)
11-28 13:23:12.561  8742  8742 E NXT_LOGGER:    at com.jagex.android.MainActivity.onCreate(Unknown Source:19)
11-28 13:23:12.561  8742  8742 E NXT_LOGGER:    at android.app.Activity.performCreate(Activity.java:8006)
11-28 13:23:12.561  8742  8742 E NXT_LOGGER:    at android.app.Activity.performCreate(Activity.java:7990)
11-28 13:23:12.561  8742  8742 E NXT_LOGGER:    at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1329)
11-28 13:23:12.561  8742  8742 E NXT_LOGGER:    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3589)
11-28 13:23:12.561  8742  8742 E NXT_LOGGER:    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3780)
11-28 13:23:12.561  8742  8742 E NXT_LOGGER:    at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
11-28 13:23:12.561  8742  8742 E NXT_LOGGER:    at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
11-28 13:23:12.561  8742  8742 E NXT_LOGGER:    at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
11-28 13:23:12.561  8742  8742 E NXT_LOGGER:    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2251)
11-28 13:23:12.561  8742  8742 E NXT_LOGGER:    at android.os.Handler.dispatchMessage(Handler.java:106)
11-28 13:23:12.561  8742  8742 E NXT_LOGGER:    at android.os.Looper.loop(Looper.java:233)
11-28 13:23:12.561  8742  8742 E NXT_LOGGER:    at android.app.ActivityThread.main(ActivityThread.java:8063)
11-28 13:23:12.561  8742  8742 E NXT_LOGGER:    at java.lang.reflect.Method.invoke(Native Method)
11-28 13:23:12.561  8742  8742 E NXT_LOGGER:    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:631)
11-28 13:23:12.561  8742  8742 E NXT_LOGGER:    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:978)
11-28 13:23:12.563  1795  2210 D ConnectivityService: NetReassign [no changes]
11-28 13:23:12.565  8742 27677 I DpmTcmClient: RegisterTcmMonitor from: $Proxy1
11-28 13:23:12.568  8742 27678 E ldscape.androi: No implementation found for void com.jagex.android.ApplicationContext.onUpdateInternetAvailable(boolean, boolean) (tried Java_com_jagex_android_ApplicationContext_onUpdateInternetAvailable and Java_com_jagex_android_ApplicationContext_onUpdateInternetAvailable__ZZ)
11-28 13:23:12.577  8742 27678 E NXT_LOGGER: attempted to call onUpdateInternetAvailable but its not yet available - network state may be incorrect
11-28 13:23:12.577  8742 27678 E NXT_LOGGER: java.lang.UnsatisfiedLinkError: No implementation found for void com.jagex.android.ApplicationContext.onUpdateInternetAvailable(boolean, boolean) (tried Java_com_jagex_android_ApplicationContext_onUpdateInternetAvailable and Java_com_jagex_android_ApplicationContext_onUpdateInternetAvailable__ZZ)
11-28 13:23:12.577  8742 27678 E NXT_LOGGER:    at com.jagex.android.ApplicationContext.onUpdateInternetAvailable(Native Method)
11-28 13:23:12.577  8742 27678 E NXT_LOGGER:    at com.jagex.android.ApplicationContext.a(Unknown Source:73)
11-28 13:23:12.577  8742 27678 E NXT_LOGGER:    at com.jagex.android.ApplicationContext.a(Unknown Source:0)
11-28 13:23:12.577  8742 27678 E NXT_LOGGER:    at com.jagex.android.ApplicationContext$b.onCapabilitiesChanged(Unknown Source:2)
11-28 13:23:12.577  8742 27678 E NXT_LOGGER:    at android.net.ConnectivityManager$NetworkCallback.onAvailable(ConnectivityManager.java:3421)
11-28 13:23:12.577  8742 27678 E NXT_LOGGER:    at android.net.ConnectivityManager$CallbackHandler.handleMessage(ConnectivityManager.java:3705)
11-28 13:23:12.577  8742 27678 E NXT_LOGGER:    at android.os.Handler.dispatchMessage(Handler.java:106)
11-28 13:23:12.577  8742 27678 E NXT_LOGGER:    at android.os.Looper.loop(Looper.java:233)
11-28 13:23:12.577  8742 27678 E NXT_LOGGER:    at android.os.HandlerThread.run(HandlerThread.java:67)

11-28 13:23:12.773  1795  2009 D ArtManagerInternalImpl: /data/misc/iorapd/com.jagex.oldscape.android/2090283/com.jagex.android.MainActivity/compiled_traces/compiled_trace.pb doesn't exist


Another one that seems less related:
11-28 13:13:54.777  8772  8802 I Finsky  : [47514] kap.f(1): getDownload(4403)
11-28 13:13:54.779 11791 13005 I Finsky:background: [47673] jxp.e(1): getDownload(request_id=4403)
11-28 13:13:54.791  7397  7825 W NamedFutures: (REDACTED) Timeout future task has been cancelled: %d milliseconds
11-28 13:13:54.792   757   757 I Zygote  : Process 12147 exited due to signal 9 (Killed)
11-28 13:13:54.681  1795  7259 W ProcessStats: setState index out of bounds. index: -1 length: 20
11-28 13:13:54.797  1795  7270 W ProcessStats: setState index out of bounds. index: -1 length: 20
11-28 13:13:54.800  8772 12417 I Finsky  : [47614] naq.P(2): IQ: Notifying installation update. [Package:com.google.android.googlequicksearchbox, isid:AiWbg8QeRayHWUBh_cixWg], status=DOWNLOADING
11-28 13:13:54.802  1795  2004 I libprocessgroup: Successfully killed process cgroup uid 1010165 pid 12147 in 111ms
11-28 13:13:54.806  7397  7397 E A       : (REDACTED) Task %s failed or timed out. Client %d disconnecting from SearchService!
11-28 13:13:54.806  7397  7397 E A       : java.util.concurrent.CancellationException: Task was cancelled.
11-28 13:13:54.806  7397  7397 E A       :      at com.google.common.util.concurrent.d.s(PG:3)
11-28 13:13:54.806  7397  7397 E A       :      at com.google.common.util.concurrent.d.get(PG:4)
11-28 13:13:54.806  7397  7397 E A       :      at com.google.common.util.concurrent.ed.a(PG:1)
11-28 13:13:54.806  7397  7397 E A       :      at com.google.common.util.concurrent.cj.r(PG:2)
11-28 13:13:54.806  7397  7397 E A       :      at com.google.common.util.concurrent.cc.run(PG:4)
11-28 13:13:54.806  7397  7397 E A       :      at com.google.android.apps.gsa.shared.util.c.a.ba.run(PG:1)
11-28 13:13:54.806  7397  7397 E A       :      at android.os.Handler.handleCallback(Handler.java:938)
11-28 13:13:54.806  7397  7397 E A       :      at android.os.Handler.dispatchMessage(Handler.java:99)
11-28 13:13:54.806  7397  7397 E A       :      at android.os.Looper.loop(Looper.java:233)
11-28 13:13:54.806  7397  7397 E A       :      at android.app.ActivityThread.main(ActivityThread.java:8063)
11-28 13:13:54.806  7397  7397 E A       :      at java.lang.reflect.Method.invoke(Native Method)
11-28 13:13:54.806  7397  7397 E A       :      at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:631)
11-28 13:13:54.806  7397  7397 E A       :      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:978)
11-28 13:13:54.810  7397 10870 E BgTaskExecutorImpl: (REDACTED) %s background task %s was cancelled.
11-28 13:13:54.810  7397 10870 E BgTaskExecutorImpl: java.util.concurrent.CancellationException: Task was cancelled.
11-28 13:13:54.810  7397 10870 E BgTaskExecutorImpl:    at com.google.common.util.concurrent.d.s(PG:3)
11-28 13:13:54.810  7397 10870 E BgTaskExecutorImpl:    at com.google.common.util.concurrent.d.get(PG:4)
11-28 13:13:54.810  7397 10870 E BgTaskExecutorImpl:    at com.google.common.util.concurrent.ed.a(PG:1)
11-28 13:13:54.810  7397 10870 E BgTaskExecutorImpl:    at com.google.common.util.concurrent.cj.r(PG:2)
11-28 13:13:54.810  7397 10870 E BgTaskExecutorImpl:    at com.google.common.util.concurrent.cc.run(PG:4)
11-28 13:13:54.810  7397 10870 E BgTaskExecutorImpl:    at com.google.android.apps.gsa.shared.util.c.a.ce.b(PG:1)
11-28 13:13:54.810  7397 10870 E BgTaskExecutorImpl:    at com.google.android.apps.gsa.shared.util.c.a.ch.run(PG:1)
11-28 13:13:54.810  7397 10870 E BgTaskExecutorImpl:    at com.google.android.libraries.i.ad.run(PG:1)
11-28 13:13:54.810  7397 10870 E BgTaskExecutorImpl:    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
11-28 13:13:54.810  7397 10870 E BgTaskExecutorImpl:    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
11-28 13:13:54.810  7397 10870 E BgTaskExecutorImpl:    at com.google.android.libraries.i.i.run(PG:2)
11-28 13:13:54.810  7397 10870 E BgTaskExecutorImpl:    at com.google.android.libraries.i.p.run(PG:3)
11-28 13:13:54.810  7397 10870 E BgTaskExecutorImpl:    at java.lang.Thread.run(Thread.java:923)
11-28 13:13:54.825 11791 13013 I Finsky:background: [47678] jxp.d(21): onGetDownload(request_id=4403, files_to_download=1, group_id=com.google.android.googlequicksearchbox, display_data[invisible=false, title=Google], network_restrictions=2, status=succeeded, bytes_downloaded=64625764, total_bytes=64625764, retry[count=0, next_retry=n/a])
```

**Emulator or device (please complete the following information):**
- Device/Emulator: OnePlus N10 5G
- OS: LineageOS
- Arch: arm64-v8a

**Additional context**
Let me know if there's something that I can search for in logcat that can help.

**Comment by ghost** [comment]
Should be resolved now. Const pushed fixes last night

**Comment by Krulvis** [comment]
Yes, we good!
