### ISSUE TITLE
[BUG] New install fails to download client

### ISSUE THREAD

**Issue by ghost** [powbot/issues#174]
**Describe the bug**
Created a new instance on BS, got this error after installing the game+stub

**Logs**
```
12-03 19:51:53.592  4015  4051 I System.out: GRABBED RESOURCE x86_64
12-03 19:51:53.592  4015  4051 W System.err: java.lang.NullPointerException: Attempt to invoke virtual method 'java.io.InputStream java.net.URL.openStream()' on a null object reference
12-03 19:51:53.592  4015  4051 W System.err:    at org.powbot.mobile.rlib.RPowBot.load(RPowBot.kt:139)
12-03 19:51:53.593  4015  4051 W System.err:    at org.powbot.mobile.BotManager.init(BotManager.kt:166)
12-03 19:51:53.593  4015  4051 W System.err:    at org.powbot.mobile.PBNativeActivity.run(PBNativeActivity.java:161)
12-03 19:51:53.593  4015  4051 W System.err:    at java.lang.Thread.run(Thread.java:764)
```

**Comment by ghost** [comment]
flushed dns, works now
