### ISSUE TITLE
[BUG] Client crash caused by ClassNotFoundException

### ISSUE THREAD

**Issue by ghost** [powbot/issues#182]
**Describe the bug**
Game crash due to a missing class / wrong version of okhttp

**Logs**
```
--------- beginning of crash
10-19 22:08:12.213 25504 25904 E AndroidRuntime: FATAL EXCEPTION: grpc-default-executor-0
10-19 22:08:12.213 25504 25904 E AndroidRuntime: Process: com.jagex.oldscape.android, PID: 25504
10-19 22:08:12.213 25504 25904 E AndroidRuntime: java.lang.ClassNotFoundException: Didn't find class "ws.EchoWebSocketListener" on path: DexPathList[[zip file "/data/user/0/com.jagex.oldscape.android/cache/powbot22898849414730495101666213692209.dx"],nativeLibraryDirectories=[/system/lib64, /system_ext/lib64]]
10-19 22:08:12.213 25504 25904 E AndroidRuntime: 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:259)
10-19 22:08:12.213 25504 25904 E AndroidRuntime: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
10-19 22:08:12.213 25504 25904 E AndroidRuntime: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
10-19 22:08:12.213 25504 25904 E AndroidRuntime: 	at org.powbot.mobile.script.ScriptLoader.getScripts(ScriptLoader.kt:51)
10-19 22:08:12.213 25504 25904 E AndroidRuntime: 	at z.cOM6.false(LocalScriptServiceImpl.kt:31)
10-19 22:08:12.213 25504 25904 E AndroidRuntime: 	at z.cOM6.start(LocalScriptServiceImpl.kt:19)
10-19 22:08:12.213 25504 25904 E AndroidRuntime: 	at org.powbot.mobile.script.LocalScriptUploaderGrpc$MethodHandlers.invoke(LocalScriptUploaderGrpc.java:231)
10-19 22:08:12.213 25504 25904 E AndroidRuntime: 	at io.grpc.stub.ServerCalls$UnaryServerCallHandler$UnaryServerCallListener.onHalfClose(ServerCalls.java:182)
10-19 22:08:12.213 25504 25904 E AndroidRuntime: 	at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.halfClosed(ServerCallImpl.java:354)
10-19 22:08:12.213 25504 25904 E AndroidRuntime: 	at io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1HalfClosed.runInContext(ServerImpl.java:866)
10-19 22:08:12.213 25504 25904 E AndroidRuntime: 	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
10-19 22:08:12.213 25504 25904 E AndroidRuntime: 	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:133)
10-19 22:08:12.213 25504 25904 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
10-19 22:08:12.213 25504 25904 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
10-19 22:08:12.213 25504 25904 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:1012)
10-19 22:08:12.213 25504 25904 E AndroidRuntime: 	Suppressed: java.lang.NoClassDefFoundError: Failed resolution of: Lokhttp3/WebSocketListener;
10-19 22:08:12.213 25504 25904 E AndroidRuntime: 		at dalvik.system.DexFile.defineClassNative(Native Method)
10-19 22:08:12.213 25504 25904 E AndroidRuntime: 		at dalvik.system.DexFile.defineClass(DexFile.java:298)
10-19 22:08:12.213 25504 25904 E AndroidRuntime: 		at dalvik.system.DexFile.loadClassBinaryName(DexFile.java:291)
10-19 22:08:12.213 25504 25904 E AndroidRuntime: 		at dalvik.system.DexPathList$Element.findClass(DexPathList.java:772)
10-19 22:08:12.213 25504 25904 E AndroidRuntime: 		at dalvik.system.DexPathList.findClass(DexPathList.java:532)
10-19 22:08:12.213 25504 25904 E AndroidRuntime: 		at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:245)
10-19 22:08:12.213 25504 25904 E AndroidRuntime: 		... 14 more
10-19 22:08:12.213 25504 25904 E AndroidRuntime: 	Caused by: java.lang.ClassNotFoundException: Didn't find class "okhttp3.WebSocketListener" on path: DexPathList[[zip file "/data/user/0/com.jagex.oldscape.android/cache/powbot22898849414730495101666213692209.dx"],nativeLibraryDirectories=[/system/lib64, /system_ext/lib64]]
10-19 22:08:12.213 25504 25904 E AndroidRuntime: 		at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:259)
10-19 22:08:12.213 25504 25904 E AndroidRuntime: 		at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
10-19 22:08:12.213 25504 25904 E AndroidRuntime: 		at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
10-19 22:08:12.213 25504 25904 E AndroidRuntime: 		... 20 more
```

```
10-19 22:09:46.153 26116 26551 W ldscape.androi: Unsupported class loader
10-19 22:09:46.153 26116 26551 W ldscape.androi: Unsupported class loader
10-19 22:09:46.153 26116 26551 W ldscape.androi: Unsupported class loader
10-19 22:09:46.154  2716  7503 E system_server: Invalid class loader spec: =UnsupportedClassLoaderContext=
10-19 22:09:46.154  2716  7503 E PackageDexUsage: Unsupported context?
10-19 22:09:46.157 26116 26551 E AndroidRuntime: FATAL EXCEPTION: grpc-default-executor-0
10-19 22:09:46.157 26116 26551 E AndroidRuntime: Process: com.jagex.oldscape.android, PID: 26116
10-19 22:09:46.157 26116 26551 E AndroidRuntime: java.lang.ClassNotFoundException: Didn't find class "ws.EchoWebSocketListener" on path: DexPathList[[zip file "/data/user/0/com.jagex.oldscape.android/cache/powbot12933797377427345021666213786152.dx"],nativeLibraryDirectories=[/system/lib64, /system_ext/lib64]]
10-19 22:09:46.157 26116 26551 E AndroidRuntime: 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:259)
10-19 22:09:46.157 26116 26551 E AndroidRuntime: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
10-19 22:09:46.157 26116 26551 E AndroidRuntime: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
10-19 22:09:46.157 26116 26551 E AndroidRuntime: 	at org.powbot.mobile.script.ScriptLoader.getScripts(ScriptLoader.kt:51)
10-19 22:09:46.157 26116 26551 E AndroidRuntime: 	at z.cOM6.false(LocalScriptServiceImpl.kt:31)
10-19 22:09:46.157 26116 26551 E AndroidRuntime: 	at z.cOM6.start(LocalScriptServiceImpl.kt:19)
10-19 22:09:46.157 26116 26551 E AndroidRuntime: 	at org.powbot.mobile.script.LocalScriptUploaderGrpc$MethodHandlers.invoke(LocalScriptUploaderGrpc.java:231)
10-19 22:09:46.157 26116 26551 E AndroidRuntime: 	at io.grpc.stub.ServerCalls$UnaryServerCallHandler$UnaryServerCallListener.onHalfClose(ServerCalls.java:182)
10-19 22:09:46.157 26116 26551 E AndroidRuntime: 	at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.halfClosed(ServerCallImpl.java:354)
10-19 22:09:46.157 26116 26551 E AndroidRuntime: 	at io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1HalfClosed.runInContext(ServerImpl.java:866)
10-19 22:09:46.157 26116 26551 E AndroidRuntime: 	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
10-19 22:09:46.157 26116 26551 E AndroidRuntime: 	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:133)
10-19 22:09:46.157 26116 26551 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
10-19 22:09:46.157 26116 26551 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
10-19 22:09:46.157 26116 26551 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:1012)
10-19 22:09:46.157 26116 26551 E AndroidRuntime: 	Suppressed: java.lang.NoClassDefFoundError: Failed resolution of: Lokhttp3/WebSocketListener;
10-19 22:09:46.157 26116 26551 E AndroidRuntime: 		at dalvik.system.DexFile.defineClassNative(Native Method)
10-19 22:09:46.157 26116 26551 E AndroidRuntime: 		at dalvik.system.DexFile.defineClass(DexFile.java:298)
10-19 22:09:46.157 26116 26551 E AndroidRuntime: 		at dalvik.system.DexFile.loadClassBinaryName(DexFile.java:291)
10-19 22:09:46.157 26116 26551 E AndroidRuntime: 		at dalvik.system.DexPathList$Element.findClass(DexPathList.java:772)
10-19 22:09:46.157 26116 26551 E AndroidRuntime: 		at dalvik.system.DexPathList.findClass(DexPathList.java:532)
10-19 22:09:46.157 26116 26551 E AndroidRuntime: 		at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:245)
10-19 22:09:46.157 26116 26551 E AndroidRuntime: 		... 14 more
10-19 22:09:46.157 26116 26551 E AndroidRuntime: 	Caused by: java.lang.ClassNotFoundException: Didn't find class "okhttp3.WebSocketListener" on path: DexPathList[[zip file "/data/user/0/com.jagex.oldscape.android/cache/powbot12933797377427345021666213786152.dx"],nativeLibraryDirectories=[/system/lib64, /system_ext/lib64]]
10-19 22:09:46.157 26116 26551 E AndroidRuntime: 		at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:259)
10-19 22:09:46.157 26116 26551 E AndroidRuntime: 		at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
10-19 22:09:46.157 26116 26551 E AndroidRuntime: 		at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
10-19 22:09:46.157 26116 26551 E AndroidRuntime: 		... 20 more
```

**Comment by ghost** [comment]
Fixed, was due to client obfuscation issues iirc
