### ISSUE TITLE
[BUG] AutoLogin solver causes client crash due to NPE

### ISSUE THREAD

**Issue by ghost** [powbot/issues#184]
**Describe the bug**
AutoLogin sometimes causes a client crash, not too sure but a user reported this to me. Had a look through the logs which are below

**To Reproduce/Line of code causing issue**
Open client, start script with account selected

**Logs**

```
--------- beginning of crash
12-15 11:59:46.800 12074 12546 E AndroidRuntime: FATAL EXCEPTION: Daemons
12-15 11:59:46.800 12074 12546 E AndroidRuntime: Process: com.jagex.oldscape.android, PID: 12074
12-15 11:59:46.800 12074 12546 E AndroidRuntime: java.lang.NullPointerException: when (it) {
12-15 11:59:46.800 12074 12546 E AndroidRuntime:                 '\n' -> {
12-15 11:59:46.800 12074 12546 E AndroidRuntime:                     arrayOf(
12-15 11:59:46.800 12074 12546 E AndroidRuntime:                         createKeyEvent(0, KeyEvent.KEYCODE_ENTER, 0, 22),
12-15 11:59:46.800 12074 12546 E AndroidRuntime:                         createKeyEvent(1, KeyEvent.KEYCODE_ENTER, 0, 22)
12-15 11:59:46.800 12074 12546 E AndroidRuntime:                     )
12-15 11:59:46.800 12074 12546 E AndroidRuntime:                 }
12-15 11:59:46.800 12074 12546 E AndroidRuntime:                 '\t' -> {
12-15 11:59:46.800 12074 12546 E AndroidRuntime:                     arrayOf(
12-15 11:59:46.800 12074 12546 E AndroidRuntime:                         createKeyEvent(0, KeyEvent.KEYCODE_TAB, 15, 8),
12-15 11:59:46.800 12074 12546 E AndroidRuntime:                         createKeyEvent(1, KeyEvent.KEYCODE_TAB, 15, 8)
12-15 11:59:46.800 12074 12546 E AndroidRuntime:                     )
12-15 11:59:46.800 12074 12546 E AndroidRuntime:                 }
12-15 11:59:46.800 12074 12546 E AndroidRuntime:                 '\b' -> {
12-15 11:59:46.800 12074 12546 E AndroidRuntime:                     arrayOf(
12-15 11:59:46.800 12074 12546 E AndroidRuntime:                         createKeyEvent(0, KeyEvent.KEYCODE_DEL, 0, 6),
12-15 11:59:46.800 12074 12546 E AndroidRuntime:                         createKeyEvent(1, KeyEvent.KEYCODE_DEL, 14, 6),
12-15 11:59:46.800 12074 12546 E AndroidRuntime:                         createKeyEvent(1, KeyEvent.KEYCODE_DEL, 14, 8)
12-15 11:59:46.800 12074 12546 E AndroidRuntime:                     )
12-15 11:59:46.800 12074 12546 E AndroidRuntime:                 }
12-15 11:59:46.800 12074 12546 E AndroidRuntime:                 else -> {
12-15 11:59:46.800 12074 12546 E AndroidRuntime:                     keyCharMap.getEvents(arrayOf(it).toCharArray())
12-15 11:59:46.800 12074 12546 E AndroidRuntime:                 }
12-15 11:59:46.800 12074 12546 E AndroidRuntime:             } must not be null
12-15 11:59:46.800 12074 12546 E AndroidRuntime: 	at org.powbot.mobile.input.Keyboard.type(Keyboard.kt:67)
12-15 11:59:46.800 12074 12546 E AndroidRuntime: 	at org.powbot.api.Input.send(Input.kt:105)
12-15 11:59:46.800 12074 12546 E AndroidRuntime: 	at org.powbot.mobile.script.daemon.AutoLoginKt.enterCredential(AutoLogin.kt:609)
12-15 11:59:46.800 12074 12546 E AndroidRuntime: 	at org.powbot.mobile.script.daemon.AutoLoginKt.login(AutoLogin.kt:591)
12-15 11:59:46.800 12074 12546 E AndroidRuntime: 	at org.powbot.mobile.script.daemon.AutoLogin.execute(AutoLogin.kt:435)
12-15 11:59:46.800 12074 12546 E AndroidRuntime: 	at org.powbot.mobile.script.ScriptManager.runDaemons(ScriptManager.kt:315)
12-15 11:59:46.800 12074 12546 E AndroidRuntime: 	at org.powbot.mobile.script.ScriptManager.access$runDaemons(ScriptManager.kt:27)
12-15 11:59:46.800 12074 12546 E AndroidRuntime: 	at org.powbot.mobile.script.ScriptManager$runDaemons$1.invokeSuspend(Unknown Source:14)
12-15 11:59:46.800 12074 12546 E AndroidRuntime: 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
12-15 11:59:46.800 12074 12546 E AndroidRuntime: 	at kotlinx.coroutines.DispatchedTaskKt.resume(DispatchedTask.kt:234)
12-15 11:59:46.800 12074 12546 E AndroidRuntime: 	at kotlinx.coroutines.DispatchedTaskKt.dispatch(DispatchedTask.kt:166)
12-15 11:59:46.800 12074 12546 E AndroidRuntime: 	at kotlinx.coroutines.CancellableContinuationImpl.dispatchResume(CancellableContinuationImpl.kt:398)
12-15 11:59:46.800 12074 12546 E AndroidRuntime: 	at kotlinx.coroutines.CancellableContinuationImpl.resumeImpl(CancellableContinuationImpl.kt:432)
12-15 11:59:46.800 12074 12546 E AndroidRuntime: 	at kotlinx.coroutines.CancellableContinuationImpl.resumeImpl$default(CancellableContinuationImpl.kt:421)
12-15 11:59:46.800 12074 12546 E AndroidRuntime: 	at kotlinx.coroutines.CancellableContinuationImpl.resumeUndispatched(CancellableContinuationImpl.kt:519)
12-15 11:59:46.800 12074 12546 E AndroidRuntime: 	at kotlinx.coroutines.ResumeUndispatchedRunnable.run(Executors.kt:161)
12-15 11:59:46.800 12074 12546 E AndroidRuntime: 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:459)
12-15 11:59:46.800 12074 12546 E AndroidRuntime: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
12-15 11:59:46.800 12074 12546 E AndroidRuntime: 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
12-15 11:59:46.800 12074 12546 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
12-15 11:59:46.800 12074 12546 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
12-15 11:59:46.800 12074 12546 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:764)
12-15 11:59:46.819  1396  1407 W ActivityManager: crash : com.jagex.oldscape.android,0
```

**Emulator or device (please complete the following information):**
 - Device/Emulator: Device
 - OS: Android 9
 - Arch: ARM64

**Comment by constt** [comment]
@Protoprize maybe pushed a fix but bit unsure here

**Comment by FlameK** [comment]
@constt is it on dev build? If so I can test it out

**Comment by FlameK** [comment]
just tested and seems to work now, thanks!
