### ISSUE TITLE
[CRASH] ItemPriceService (used by paint) causes crash

### ISSUE THREAD

**Issue by Krulvis** [powbot/issues#214]
**Describe the bug**
Tracking inventory items causes a crash when getting price.

**To Reproduce/Line of code causing issue**
Add fire battlestaff to inventory tracker (haven't tested other items)
```
paintBuilder.trackInventoryItems(1393)
```

**Expected behavior**
Fire battlestaffs to appear in paint with price added.

**Logs**
```
02-11 10:57:49.564 26172 27446 E AndroidRuntime: FATAL EXCEPTION: DefaultDispatcher-worker-6
02-11 10:57:49.564 26172 27446 E AndroidRuntime: Process: com.jagex.oldscape.android, PID: 26172
02-11 10:57:49.564 26172 27446 E AndroidRuntime: kotlin.UninitializedPropertyAccessException: lateinit property cache has not been initialized
02-11 10:57:49.564 26172 27446 E AndroidRuntime:        at org.powbot.mobile.service.AUX.this(ItemPriceService.kt:54)
02-11 10:57:49.564 26172 27446 E AndroidRuntime:        at org.powbot.api.script.paint.InventoryItemPaintItem$onGameTick$1.invokeSuspend(PaintItem.kt:378)
02-11 10:57:49.564 26172 27446 E AndroidRuntime:        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
02-11 10:57:49.564 26172 27446 E AndroidRuntime:        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
02-11 10:57:49.564 26172 27446 E AndroidRuntime:        at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:42)
02-11 10:57:49.564 26172 27446 E AndroidRuntime:        at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
02-11 10:57:49.564 26172 27446 E AndroidRuntime:        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
02-11 10:57:49.564 26172 27446 E AndroidRuntime:        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:749)
02-11 10:57:49.564 26172 27446 E AndroidRuntime:        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
02-11 10:57:49.564 26172 27446 E AndroidRuntime:        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
02-11 10:57:49.564 26172 27446 E AndroidRuntime:        Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@bb4dcbc, Dispatchers.IO]
```

**Comment by iDznPB** [comment]
Was just about to report the same thing, but can confirm it's any item in the item tracker for paint 👍

**Comment by constt** [comment]
should be fixed

**Comment by iDznPB** [comment]
Tested and working thanks!
Will leave open in case @Krulvis has any further comments
