### ISSUE TITLE
RsCache ItemLoader does not work [BUG]

### ISSUE THREAD

**Issue by ghost** [powbot/issues#29]
**Describe the bug**
When searching for widgets by ItemID/any item related func, it will crash the script 

**To Reproduce/Line of code causing issue**
```Components.stream().filtered(it -> it.itemId() == 1).first()```

**Logs**
```
[SEVERE] java.lang.NoSuchMethodError: No virtual method load(I)Ljava/lang/Object; in class Lorg/powbot/mobile/rscache/loader/ItemLoader; or its super classes (declaration of 'org.powbot.mobile.rscache.loader.ItemLoader' appears in /data/user/0/com.jagex.oldscape.android/no_backup/powbot.apk!classes8.dex)
	at org.powbot.common.helpers.InterfacesHelper$createItemInterface$1.invoke(InterfacesHelper.kt:19)
	at org.powbot.common.helpers.InterfacesHelper$createItemInterface$1.invoke(InterfacesHelper.kt:18)
	at org.powbot.api.rt4.stream.SimpleStream.byte(SimpleStream.kt:54)
	at org.powbot.api.rt4.stream.SimpleStream.lambda$WXsEG2DHh4z66C1084A5HwiTWKc(Unknown Source:0)
	at org.powbot.api.rt4.stream.-$$Lambda$SimpleStream$WXsEG2DHh4z66C1084A5HwiTWKc.test(Unknown Source:2)
	at org.powbot.api.rt4.stream.SimpleStream.byte(SimpleStream.kt:161)
	at org.powbot.api.rt4.stream.SimpleStream.lambda$EVit6gy-ZTmj6FLPfltOTmOhSEs(Unknown Source:0)
	at org.powbot.api.rt4.stream.-$$Lambda$SimpleStream$EVit6gy-ZTmj6FLPfltOTmOhSEs.test(Unknown Source:2)
	at org.powbot.api.rt4.Components.byte(Components.kt:74)
	at org.powbot.api.rt4.Components.access$getComponents(Components.kt:9)
	at org.powbot.api.rt4.Components$backingProvider$1.getComponents(Components.kt:20)
	at org.powbot.api.rt4.Components$backingProvider$1.first(Components.kt:45)
	at org.powbot.api.rt4.Components$backingProvider$1.first(Components.kt:12)
	at org.powbot.api.rt4.stream.SimpleStream.firstOrNull(SimpleStream.kt:161)
	at org.powbot.api.rt4.stream.SimpleStream.first(SimpleStream.kt:142)
	at org.powbot.common.helpers.InterfacesHelper.createItemInterface(InterfacesHelper.kt:21)
	at org.powbot.common.tasks.CombineInterfaceTask.run(CombineInterfaceTask.kt:45)
	at org.powbot.common.BaseTask.execute(BaseTask.kt:35)
	at org.powbot.crafting.CraftingTask.run(CraftingTask.kt:147)
	at org.powbot.common.TaskScript.poll(TaskScript.kt:39)
	at org.powbot.mobile.script.ScriptManager$runScript$4.invokeSuspend(ScriptManager.kt:371)
	at org.powbot.mobile.script.ScriptManager$runScript$4.invoke(Unknown Source:8)
	at org.powbot.mobile.script.ScriptManager$runScript$4.invoke(Unknown Source:4)
	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturnIgnoreTimeout(Undispatched.kt:100)
	at kotlinx.coroutines.TimeoutKt.setupTimeout(Timeout.kt:146)
	at kotlinx.coroutines.TimeoutKt.withTimeout(Timeout.kt:44)
	at org.powbot.mobile.script.ScriptManager.runScript(ScriptManager.kt:369)
	at org.powbot.mobile.script.ScriptManager.access$runScript(ScriptManager.kt:25)
	at org.powbot.mobile.script.ScriptManager$runScript$1.invokeSuspend(Unknown Source:14)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:749)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)

```

**Comment by constt** [comment]
@Protoprize still an issue?

**Comment by ghost** [comment]
@constt  Still happening

**Comment by constt** [comment]
@Protoprize should be fixed now

**Comment by MichalTDev** [comment]
Fixed :)

**Comment by ghost** [comment]
Fixed 👍
