### ISSUE TITLE
[BUG] Objects.Stream() Causes ArrayOutOfBoundsException

### ISSUE THREAD

**Issue by iDznPB** [powbot/issues#48]
**Describe the bug**
[SEVERE] script poll failed (TestScript99)
[SEVERE] java.lang.ArrayIndexOutOfBoundsException: length=32; index=-1

**To Reproduce/Line of code causing issue**
```
Bank.nearest().distanceTo(Players.local())
```

**Expected behavior**
return the distance or compare the distance to player

**Logs**
```
[SEVERE] script poll failed (TestScript99)
[SEVERE] java.lang.ArrayIndexOutOfBoundsException: length=32; index=-1
	at org.powbot.api.rt4.GameObject.id(GameObject.kt:126)
	at org.powbot.api.rt4.GameObject$specificObjectConfig$2.invoke(GameObject.kt:164)
	at org.powbot.api.rt4.GameObject$specificObjectConfig$2.invoke(GameObject.kt:163)
	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
	at org.powbot.api.rt4.GameObject.long(GameObject.kt:163)
	at org.powbot.api.rt4.GameObject.actions(GameObject.kt:227)
	at org.powbot.api.rt4.Bank.long(Bank.kt:65)
	at org.powbot.api.rt4.Bank.access$UNREACHABLE_FILTER(Bank.kt:33)
	at org.powbot.api.rt4.Bank$getBank$obj$1.invoke(Bank.kt:97)
	at org.powbot.api.rt4.Bank$getBank$obj$1.invoke(Bank.kt:97)
	at org.powbot.api.rt4.stream.SimpleStream.long(SimpleStream.kt:54)
	at org.powbot.api.rt4.stream.SimpleStream.lambda$CTjJA0-eAHo_DiydUlt5geVKBkM(Unknown Source:0)
	at org.powbot.api.rt4.stream.-$$Lambda$SimpleStream$CTjJA0-eAHo_DiydUlt5geVKBkM.test(Unknown Source:2)
	at org.powbot.api.rt4.stream.SimpleStream.final(SimpleStream.kt:161)
	at org.powbot.api.rt4.stream.SimpleStream.lambda$Kv4_Xu-IfpnsTWuEgDFk0lHXPFw(Unknown Source:0)
	at org.powbot.api.rt4.stream.-$$Lambda$SimpleStream$Kv4_Xu-IfpnsTWuEgDFk0lHXPFw.test(Unknown Source:2)
	at org.powbot.api.rt4.Objects.long(Objects.kt:158)
	at org.powbot.api.rt4.Objects.get(Objects.kt:118)
	at org.powbot.api.rt4.Objects$source$1.first(Objects.kt:61)
	at org.powbot.api.rt4.Objects$source$1.first(Objects.kt:20)
	at org.powbot.api.rt4.stream.SimpleStream.firstOrNull(SimpleStream.kt:161)
	at org.powbot.api.rt4.Bank.getBank(Bank.kt:98)
	at org.powbot.api.rt4.Bank.nearest(Bank.kt:113)
	at Tests.Test.poll(Test.java:64)
	at org.powbot.mobile.script.ScriptManager$runScript$4.invokeSuspend(ScriptManager.kt:372)
	at org.powbot.mobile.script.ScriptManager$runScript$4.invoke(Unknown Source:8)
	at org.powbot.mobile.script.ScriptManager$runScript$4.invoke(Unknown Source:4)
	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturnIgnoreTimeout(Undispatched.kt:100)
	at kotlinx.coroutines.TimeoutKt.setupTimeout(Timeout.kt:146)
	at kotlinx.coroutines.TimeoutKt.withTimeout(Timeout.kt:44)
	at org.powbot.mobile.script.ScriptManager.runScript(ScriptManager.kt:370)
	at org.powbot.mobile.script.ScriptManager.access$runScript(ScriptManager.kt:25)
	at org.powbot.mobile.script.ScriptManager$start$2.invokeSuspend(ScriptManager.kt:162)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:749)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
```

**Emulator or device (please complete the following information):**
 - Device/Emulator: BS
 - OS: P64
 - Arch: ARM

**Comment by constt** [comment]
@iDznPB fixed in next

**Comment by iDznPB** [comment]
Resolved
