### ISSUE TITLE
Constant grabber causing crash when starting any script [BUG]

### ISSUE THREAD

**Issue by ghost** [powbot/issues#5]
**Describe the bug**

Starting any script and letting the constant grabber open, crashes the client/game

**To Reproduce/Line of code causing issue**
Start any script

**Expected behavior**
Script starts

**Logs**
```08-15 10:41:24.293  4498  4706 E AndroidRuntime: FATAL EXCEPTION: Daemons
08-15 10:41:24.293  4498  4706 E AndroidRuntime: Process: com.jagex.oldscape.android, PID: 4498
08-15 10:41:24.293  4498  4706 E AndroidRuntime: java.lang.AbstractMethodError: abstract method "long org.powerbot.script.rt4.Addressable.address()"
08-15 10:41:24.293  4498  4706 E AndroidRuntime: 	at org.powbot.api.rt4.Component.parentId(Component.kt:355)
08-15 10:41:24.293  4498  4706 E AndroidRuntime: 	at org.powbot.api.rt4.Component.parent(Component.kt:93)
08-15 10:41:24.293  4498  4706 E AndroidRuntime: 	at org.powbot.api.rt4.Component.hidden(Component.kt:266)
08-15 10:41:24.293  4498  4706 E AndroidRuntime: 	at org.powbot.api.rt4.Component.hidden(Component.kt:267)
08-15 10:41:24.293  4498  4706 E AndroidRuntime: 	at org.powbot.api.rt4.Component.hidden(Component.kt:267)
08-15 10:41:24.293  4498  4706 E AndroidRuntime: 	at org.powbot.api.rt4.Component.hidden(Component.kt:267)
08-15 10:41:24.293  4498  4706 E AndroidRuntime: 	at org.powbot.api.rt4.Component.visible(Component.kt:438)
08-15 10:41:24.293  4498  4706 E AndroidRuntime: 	at org.powbot.api.rt4.Component.valid(Component.kt:136)
08-15 10:41:24.293  4498  4706 E AndroidRuntime: 	at org.powbot.api.rt4.Component.screenPoint(Component.kt:66)
08-15 10:41:24.293  4498  4706 E AndroidRuntime: 	at org.powbot.api.rt4.Component.nextPoint(Component.kt:409)
08-15 10:41:24.293  4498  4706 E AndroidRuntime: 	at org.powbot.api.rt4.Component$calculateScreenPosition$1.call(Component.kt:489)
08-15 10:41:24.293  4498  4706 E AndroidRuntime: 	at org.powbot.api.rt4.Component$calculateScreenPosition$1.call(Component.kt:485)
08-15 10:41:24.293  4498  4706 E AndroidRuntime: 	at org.powbot.api.rt4.Interactive.click(Interactive.kt:76)
08-15 10:41:24.293  4498  4706 E AndroidRuntime: 	at org.powbot.api.rt4.Game.tab(Game.kt:113)
08-15 10:41:24.293  4498  4706 E AndroidRuntime: 	at org.powbot.mobile.script.daemon.ConstantsGrabber.execute(ConstantsGrabber.kt:28)
08-15 10:41:24.293  4498  4706 E AndroidRuntime: 	at org.powbot.mobile.script.ScriptManager.runDaemons(ScriptManager.kt:320)
08-15 10:41:24.293  4498  4706 E AndroidRuntime: 	at org.powbot.mobile.script.ScriptManager.access$runDaemons(ScriptManager.kt:25)
08-15 10:41:24.293  4498  4706 E AndroidRuntime: 	at org.powbot.mobile.script.ScriptManager$runDaemons$1.invokeSuspend(Unknown Source:14)
08-15 10:41:24.293  4498  4706 E AndroidRuntime: 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
08-15 10:41:24.293  4498  4706 E AndroidRuntime: 	at kotlinx.coroutines.DispatchedTaskKt.resume(DispatchedTask.kt:234)
08-15 10:41:24.293  4498  4706 E AndroidRuntime: 	at kotlinx.coroutines.DispatchedTaskKt.dispatch(DispatchedTask.kt:166)
08-15 10:41:24.293  4498  4706 E AndroidRuntime: 	at kotlinx.coroutines.CancellableContinuationImpl.dispatchResume(CancellableContinuationImpl.kt:397)
08-15 10:41:24.293  4498  4706 E AndroidRuntime: 	at kotlinx.coroutines.CancellableContinuationImpl.resumeImpl(CancellableContinuationImpl.kt:431)
08-15 10:41:24.293  4498  4706 E AndroidRuntime: 	at kotlinx.coroutines.CancellableContinuationImpl.resumeImpl$default(CancellableContinuationImpl.kt:420)
08-15 10:41:24.293  4498  4706 E AndroidRuntime: 	at kotlinx.coroutines.CancellableContinuationImpl.resumeUndispatched(CancellableContinuationImpl.kt:518)
08-15 10:41:24.293  4498  4706 E AndroidRuntime: 	at kotlinx.coroutines.ResumeUndispatchedRunnable.run(Executors.kt:186)
08-15 10:41:24.293  4498  4706 E AndroidRuntime: 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:458)
08-15 10:41:24.293  4498  4706 E AndroidRuntime: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
08-15 10:41:24.293  4498  4706 E AndroidRuntime: 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
08-15 10:41:24.293  4498  4706 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
08-15 10:41:24.293  4498  4706 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
08-15 10:41:24.293  4498  4706 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:764)
08-15 10:41:24.293  4498  4706 E AndroidRuntime: 	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@66e635e, java.util.concurrent.ScheduledThreadPoolExecutor@7fb233f[Running, pool size = 1, active threads = 1, queued tasks = 0, completed tasks = 1]]
08-15 10:41:24.294  1962  3557 W ActivityManager:   Force finishing activity com.jagex.oldscape.android/com.jagex.android.MainActivity```


**Emulator or device (please complete the following information):**
 - Device/Emulator: Bluestacks
 - OS: Android Pie 
 - Arch: ARM64

**Comment by constt** [comment]
@Protoprize fixed?

**Comment by ghost** [comment]
@constt Fixed :)
