### ISSUE TITLE
[BUG] error adding touch event to queue

### ISSUE THREAD

**Issue by Krulvis** [powbot/issues#50]
**Describe the bug**
Auto login fails when script is ran with launcher or from sdk

**Logs**
```
08-31 20:35:58.194 15044 28124 I AutoLogin: Cancelling as something went wrong
08-31 20:35:58.201 15044 28124 I Touchscreen: Input from [Daemons], [Daemons]
08-31 20:35:58.201 15044 28124 I System.out: Point(x=-1, y=-1)
08-31 20:35:58.202 15044 28124 W ldscape.androi: Accessing hidden field Landroid/view/MotionEvent;->mNativePtr:J (greylist-max-p, reflection, denied)
08-31 20:35:58.202 15044 28124 E Touchscreen: error adding touch event to queue
08-31 20:35:58.202 15044 28124 E Touchscreen: java.lang.NoSuchFieldException: mNativePtr
08-31 20:35:58.202 15044 28124 E Touchscreen:  at java.lang.Class.getField(Class.java:1604)
08-31 20:35:58.202 15044 28124 E Touchscreen:  at org.powbot.mobile.jni.PowBotNative$motionEventPtrField$2.invoke(PowBotNative.kt:57)
08-31 20:35:58.202 15044 28124 E Touchscreen:  at org.powbot.mobile.jni.PowBotNative$motionEventPtrField$2.invoke(PowBotNative.kt:50)
08-31 20:35:58.202 15044 28124 E Touchscreen:  at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
08-31 20:35:58.202 15044 28124 E Touchscreen:  at org.powbot.mobile.jni.PowBotNative.getMotionEventPtrField(PowBotNative.kt:50)
08-31 20:35:58.202 15044 28124 E Touchscreen:  at org.powbot.mobile.jni.PowBotNative.sendTouchEvent(PowBotNative.kt:559)
08-31 20:35:58.202 15044 28124 E Touchscreen:  at org.powbot.mobile.input.Touchscreen.offerAndWait(Touchscreen.kt:384)
08-31 20:35:58.202 15044 28124 E Touchscreen:  at org.powbot.mobile.input.Touchscreen.offerAndWait$default(Touchscreen.kt:377)
08-31 20:35:58.202 15044 28124 E Touchscreen:  at org.powbot.mobile.input.Touchscreen.tap(Touchscreen.kt:100)
08-31 20:35:58.202 15044 28124 E Touchscreen:  at org.powbot.api.Input.tap(Input.kt:206)
08-31 20:35:58.202 15044 28124 E Touchscreen:  at org.powbot.api.Input.tap(Input.kt:191)
08-31 20:35:58.202 15044 28124 E Touchscreen:  at org.powbot.api.Input.tap$default(Input.kt:190)
08-31 20:35:58.202 15044 28124 E Touchscreen:  at org.powbot.mobile.script.daemon.AutoLogin.tapAreaFromCenter(AutoLogin.kt:154)
08-31 20:35:58.202 15044 28124 E Touchscreen:  at org.powbot.mobile.script.daemon.AutoLogin.handleCancelButton(AutoLogin.kt:171)
08-31 20:35:58.202 15044 28124 E Touchscreen:  at org.powbot.mobile.script.daemon.AutoLogin.execute(AutoLogin.kt:435)
08-31 20:35:58.202 15044 28124 E Touchscreen:  at org.powbot.mobile.script.ScriptManager.runDaemons(ScriptManager.kt:321)
08-31 20:35:58.202 15044 28124 E Touchscreen:  at org.powbot.mobile.script.ScriptManager.access$runDaemons(ScriptManager.kt:25)
08-31 20:35:58.202 15044 28124 E Touchscreen:  at org.powbot.mobile.script.ScriptManager$runDaemons$1.invokeSuspend(Unknown Source:14)
08-31 20:35:58.202 15044 28124 E Touchscreen:  at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
08-31 20:35:58.202 15044 28124 E Touchscreen:  at kotlinx.coroutines.DispatchedTaskKt.resume(DispatchedTask.kt:234)
08-31 20:35:58.202 15044 28124 E Touchscreen:  at kotlinx.coroutines.DispatchedTaskKt.dispatch(DispatchedTask.kt:166)
08-31 20:35:58.202 15044 28124 E Touchscreen:  at kotlinx.coroutines.CancellableContinuationImpl.dispatchResume(CancellableContinuationImpl.kt:397)
08-31 20:35:58.202 15044 28124 E Touchscreen:  at kotlinx.coroutines.CancellableContinuationImpl.resumeImpl(CancellableContinuationImpl.kt:431)
08-31 20:35:58.202 15044 28124 E Touchscreen:  at kotlinx.coroutines.CancellableContinuationImpl.resumeImpl$default(CancellableContinuationImpl.kt:420)
08-31 20:35:58.202 15044 28124 E Touchscreen:  at kotlinx.coroutines.CancellableContinuationImpl.resumeUndispatched(CancellableContinuationImpl.kt:518)
08-31 20:35:58.202 15044 28124 E Touchscreen:  at kotlinx.coroutines.ResumeUndispatchedRunnable.run(Executors.kt:186)
08-31 20:35:58.202 15044 28124 E Touchscreen:  at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
08-31 20:35:58.202 15044 28124 E Touchscreen:  at java.util.concurrent.FutureTask.run(FutureTask.java:266)
08-31 20:35:58.202 15044 28124 E Touchscreen:  at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
08-31 20:35:58.202 15044 28124 E Touchscreen:  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
08-31 20:35:58.202 15044 28124 E Touchscreen:  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
08-31 20:35:58.202 15044 28124 E Touchscreen:  at java.lang.Thread.run(Thread.java:923)
```

**Emulator or device (please complete the following information):**
 - Device/Emulator: OnePlus N10 5G
 - OS: LineageOS
 - Arch: arm64-v8a

**additional info**
Could be similar to issue posted previously: https://github.com/powbot/issues/issues/24 which was missing class def, while I have problems finding field.

**Comment by Krulvis** [comment]
`adb shell settings put global hidden_api_policy 1` fixed it
