### ISSUE TITLE
Starting local script causing client crash [BUG]

### ISSUE THREAD

**Issue by ghost** [powbot/issues#8]
**Describe the bug**
Trying to start a simple script crashes the client

**To Reproduce/Line of code causing issue**
Try to start a simple local script, printing anything or using any API functions 

**Expected behavior**
Script starts

**Logs**

```08-15 11:35:12.390  5941  6154 E AndroidRuntime: FATAL EXCEPTION: grpc-default-executor-0
08-15 11:35:12.390  5941  6154 E AndroidRuntime: Process: com.jagex.oldscape.android, PID: 5941
08-15 11:35:12.390  5941  6154 E AndroidRuntime: kotlin.reflect.jvm.internal.KotlinReflectionInternalError: Cannot create type for an unsupported classifier: class kotlin.Unit (Kotlin reflection is not available) (class kotlin.jvm.internal.ClassReference)
08-15 11:35:12.390  5941  6154 E AndroidRuntime: 	at kotlin.reflect.full.KClassifiers.createType(KClassifiers.kt:48)
08-15 11:35:12.390  5941  6154 E AndroidRuntime: 	at kotlin.reflect.full.KClassifiers.createType$default(KClassifiers.kt:45)
08-15 11:35:12.390  5941  6154 E AndroidRuntime: 	at com.fasterxml.jackson.module.kotlin.KotlinAnnotationIntrospector.<clinit>(KotlinAnnotationIntrospector.kt:170)
08-15 11:35:12.390  5941  6154 E AndroidRuntime: 	at com.fasterxml.jackson.module.kotlin.KotlinModule.setupModule(KotlinModule.kt:121)
08-15 11:35:12.390  5941  6154 E AndroidRuntime: 	at com.fasterxml.jackson.databind.ObjectMapper.registerModule(ObjectMapper.java:853)
08-15 11:35:12.390  5941  6154 E AndroidRuntime: 	at com.fasterxml.jackson.module.kotlin.ExtensionsKt.registerKotlinModule(Extensions.kt:41)
08-15 11:35:12.390  5941  6154 E AndroidRuntime: 	at org.powbot.mobile.schedule.aUX.<clinit>(ScheduleManager.kt:32)
08-15 11:35:12.390  5941  6154 E AndroidRuntime: 	at z.COM7.const(LocalScriptServiceImpl.kt:45)
08-15 11:35:12.390  5941  6154 E AndroidRuntime: 	at z.COM7.start(LocalScriptServiceImpl.kt:19)
08-15 11:35:12.390  5941  6154 E AndroidRuntime: 	at org.powbot.mobile.script.LocalScriptUploaderGrpc$MethodHandlers.invoke(LocalScriptUploaderGrpc.java:231)
08-15 11:35:12.390  5941  6154 E AndroidRuntime: 	at io.grpc.stub.ServerCalls$UnaryServerCallHandler$UnaryServerCallListener.onHalfClose(ServerCalls.java:182)
08-15 11:35:12.390  5941  6154 E AndroidRuntime: 	at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.halfClosed(ServerCallImpl.java:354)
08-15 11:35:12.390  5941  6154 E AndroidRuntime: 	at io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1HalfClosed.runInContext(ServerImpl.java:866)
08-15 11:35:12.390  5941  6154 E AndroidRuntime: 	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
08-15 11:35:12.390  5941  6154 E AndroidRuntime: 	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:133)
08-15 11:35:12.390  5941  6154 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
08-15 11:35:12.390  5941  6154 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
08-15 11:35:12.390  5941  6154 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:764)```

**Emulator or device (please complete the following information):**
 - Device/Emulator: Bluestacks
 - OS: Android Pie
 - Arch: ARM64

**Comment by ghost** [comment]
```08-15 22:45:54.618  9289  9716 F libc    : Fatal signal 11 (SIGSEGV), code 128 (SI_KERNEL), fault addr 0x0 in tid 9716 (DefaultDispatch), pid 9289 (ldscape.android)
08-15 22:45:54.705  9745  9745 I crash_dump64: obtaining output fd from tombstoned, type: kDebuggerdTombstone
08-15 22:45:54.705  1815  1815 I /system/bin/tombstoned: received crash request for pid 9716
08-15 22:45:54.705  9745  9745 I crash_dump64: performing dump of process 9289 (target tid = 9716)
08-15 22:45:54.712  9745  9745 F DEBUG   : *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
08-15 22:45:54.712  9745  9745 F DEBUG   : Build fingerprint: 'OnePlus/OnePlus3/OnePlus3:9/PPR1.180720.122/6736742:user/release-keys'
08-15 22:45:54.712  9745  9745 F DEBUG   : Revision: '0'
08-15 22:45:54.712  9745  9745 F DEBUG   : ABI: 'x86_64'
08-15 22:45:54.712  9745  9745 F DEBUG   : pid: 9289, tid: 9716, name: DefaultDispatch  >>> com.jagex.oldscape.android <<<
08-15 22:45:54.712  9745  9745 F DEBUG   : signal 11 (SIGSEGV), code 128 (SI_KERNEL), fault addr 0x0
08-15 22:45:54.712  9745  9745 F DEBUG   :     rax 0000000092bf5a00  rbx 00007b698e590410  rcx 00007b6966b014f0  rdx 00007b6992c60f80
08-15 22:45:54.712  9745  9745 F DEBUG   :     r8  0000000001eca1a7  r9  0000000000001a70  r10 0000000000000000  r11 0000000000000000
08-15 22:45:54.712  9745  9745 F DEBUG   :     r12 00000000007f5080  r13 0000000000000000  r14 00007b6966afa404  r15 00007b698e592bb8
08-15 22:45:54.712  9745  9745 F DEBUG   :     rdi 00007b698e590000  rsi 00007b698e590070
08-15 22:45:54.712  9745  9745 F DEBUG   :     rbp 00007b698e590000  rsp 00007b6968f693f0  rip 000000000e0190ba
08-15 22:45:54.713  9745  9745 F DEBUG   :
08-15 22:45:54.713  9745  9745 F DEBUG   : backtrace:```

**Comment by ghost** [comment]
Also, noticed it now crashes **after** the Constant Grabber, compared to while it was running before (could just be luck)
