### ISSUE TITLE
[BUG] Equipment API kills poll() and causes crash

### ISSUE THREAD

**Issue by iDznPB** [powbot/issues#84]
**Describe the bug**
canCast() either returns false when it should be true, or it just straight up crashes the app.

EDIT: Turns out it's the equipment api causing the issue, canCast() checks for staves which in turn checks Equipment.
This  happens on both Equipment.itemAt() AND Equipment.stream()

**To Reproduce/Line of code causing issue**
```
Magic.Spell.HIGH_ALCHEMY.canCast();

Equipment.itemAt(Slot.HEAD).name();

Equipment.steam().name(whatever).isNotEmpty()
```

**Screenshots**
https://gyazo.com/aa001ff09c44fec75f72f98b5dd19c3c
https://gyazo.com/9ccbf6a024b065a26776ca49e72d6113

**Logs**
```
--------- beginning of crash
09-13 17:12:09.084  3493  3662 F libc    : Fatal signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x6008e1900 in tid 3662 (DefaultDispatch), pid 3493 (ldscape.android)
09-13 17:12:09.085  3493  4863 I System.out: Set lastactiontime to x
09-13 17:12:09.195  4876  4876 I crash_dump64: obtaining output fd from tombstoned, type: kDebuggerdTombstone
09-13 17:12:09.197  1768  1768 I /system/bin/tombstoned: received crash request for pid 3662
09-13 17:12:09.198  4876  4876 I crash_dump64: performing dump of process 3493 (target tid = 3662)
09-13 17:12:09.199  4876  4876 F DEBUG   : *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
09-13 17:12:09.202  4876  4876 F DEBUG   : Build fingerprint: 'OnePlus/OnePlus5/OnePlus5:9/PPR1.180720.122/6736742:user/release-keys'
09-13 17:12:09.202  4876  4876 F DEBUG   : Revision: '0'
09-13 17:12:09.202  4876  4876 F DEBUG   : ABI: 'x86_64'
09-13 17:12:09.202  4876  4876 F DEBUG   : pid: 3493, tid: 3662, name: DefaultDispatch  >>> com.jagex.oldscape.android <<<
09-13 17:12:09.202  4876  4876 F DEBUG   : signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x6008e1900
09-13 17:12:09.202  4876  4876 F DEBUG   :     rax 0000000000000100  rbx 00007c63c05c8410  rcx 00007c63ab3ff4f0  rdx 00007c63c42caf80
09-13 17:12:09.202  4876  4876 F DEBUG   :     r8  0000000001e337f6  r9  0000000000001f60  r10 0000000000000fa0  r11 00007c63d37cc000
09-13 17:12:09.202  4876  4876 F DEBUG   :     r12 00000006008e1900  r13 0000000000000000  r14 00000006008e1900  r15 00007c63c05cabb8
09-13 17:12:09.202  4876  4876 F DEBUG   :     rdi 00007c63c05c8000  rsi 00007c63c05c8070
09-13 17:12:09.202  4876  4876 F DEBUG   :     rbp 00007c63c05c8000  rsp 00007c63a4f693f0  rip 000000000de83ffd
09-13 17:12:09.209  4876  4876 F DEBUG   : 
09-13 17:12:09.209  4876  4876 F DEBUG   : backtrace:
09-13 17:12:09.209  4876  4876 F DEBUG   :     #00 pc 0000000000b77ffd  [anon:Mem_0x20000000:000000000d30c000]
09-13 17:12:09.312  3493  3504 I ldscape.androi: Background concurrent copying GC freed 376108(44MB) AllocSpace objects, 6(96KB) LOS objects, 43% free, 31MB/55MB, paused 245us total 330.999ms
09-13 17:12:09.936  1768  1768 E /system/bin/tombstoned: Tombstone written to: /data/tombstones/tombstone_33
--------- beginning of system
09-13 17:12:09.969  1909  1924 W BroadcastQueue: Background execution not allowed: receiving Intent { act=android.intent.action.DROPBOX_ENTRY_ADDED flg=0x10 (has extras) } to com.google.android.gms/.stats.service.DropBoxEntryAddedReceiver
09-13 17:12:09.969  1909  1924 W BroadcastQueue: Background execution not allowed: receiving Intent { act=android.intent.action.DROPBOX_ENTRY_ADDED flg=0x10 (has extras) } to com.google.android.gms/.chimera.GmsIntentOperationService$PersistentTrustedReceiver
09-13 17:12:09.981  1909  4879 W ActivityManager:   Force finishing activity com.jagex.oldscape.android/com.jagex.android.MainActivity
09-13 17:12:10.020  1731  1731 I Zygote  : Process 3493 exited due to signal (11)
09-13 17:12:10.022  1745  1745 E adbd    : failed to connect to socket 'tcp:61666': Connection refused
09-13 17:12:10.027  1909  4255 I WindowManager: WIN DEATH: Window{df8e368 u0 com.jagex.oldscape.android/com.jagex.android.MainActivity}
09-13 17:12:10.037  1909  4879 W ActivityManager: Exception thrown during pause
09-13 17:12:10.037  1909  4879 W ActivityManager: android.os.DeadObjectException
09-13 17:12:10.037  1909  4879 W ActivityManager: 	at android.os.BinderProxy.transactNative(Native Method)
09-13 17:12:10.037  1909  4879 W ActivityManager: 	at android.os.BinderProxy.transact(Binder.java:1129)
09-13 17:12:10.037  1909  4879 W ActivityManager: 	at android.app.IApplicationThread$Stub$Proxy.scheduleTransaction(IApplicationThread.java:1777)
09-13 17:12:10.037  1909  4879 W ActivityManager: 	at android.app.servertransaction.ClientTransaction.schedule(ClientTransaction.java:129)
09-13 17:12:10.037  1909  4879 W ActivityManager: 	at com.android.server.am.ClientLifecycleManager.scheduleTransaction(ClientLifecycleManager.java:47)
09-13 17:12:10.037  1909  4879 W ActivityManager: 	at com.android.server.am.ClientLifecycleManager.scheduleTransaction(ClientLifecycleManager.java:69)
09-13 17:12:10.037  1909  4879 W ActivityManager: 	at com.android.server.am.ActivityStack.startPausingLocked(ActivityStack.java:1476)
09-13 17:12:10.037  1909  4879 W ActivityManager: 	at com.android.server.am.ActivityStack.finishActivityLocked(ActivityStack.java:3751)
09-13 17:12:10.037  1909  4879 W ActivityManager: 	at com.android.server.am.ActivityStack.finishActivityLocked(ActivityStack.java:3693)
09-13 17:12:10.037  1909  4879 W ActivityManager: 	at com.android.server.am.ActivityStack.finishTopCrashedActivityLocked(ActivityStack.java:3576)
09-13 17:12:10.037  1909  4879 W ActivityManager: 	at com.android.server.am.ActivityStackSupervisor.finishTopCrashedActivitiesLocked(ActivityStackSupervisor.java:2291)
09-13 17:12:10.037  1909  4879 W ActivityManager: 	at com.android.server.am.AppErrors.handleAppCrashLocked(AppErrors.java:747)
09-13 17:12:10.037  1909  4879 W ActivityManager: 	at com.android.server.am.AppErrors.makeAppCrashingLocked(AppErrors.java:579)
09-13 17:12:10.037  1909  4879 W ActivityManager: 	at com.android.server.am.AppErrors.crashApplicationInner(AppErrors.java:447)
09-13 17:12:10.037  1909  4879 W ActivityManager: 	at com.android.server.am.AppErrors.crashApplication(AppErrors.java:392)
09-13 17:12:10.037  1909  4879 W ActivityManager: 	at com.android.server.am.ActivityManagerService.handleApplicationCrashInner(ActivityManagerService.java:15548)
09-13 17:12:10.037  1909  4879 W ActivityManager: 	at com.android.server.am.NativeCrashListener$NativeCrashReporter.run(NativeCrashListener.java:85)
09-13 17:12:10.046  1909  2007 W InputDispatcher: channel 'df8e368 com.jagex.oldscape.android/com.jagex.android.MainActivity (server)' ~ Consumer closed input channel or an error occurred.  events=0x9
09-13 17:12:10.046  1909  2007 E InputDispatcher: channel 'df8e368 com.jagex.oldscape.android/com.jagex.android.MainActivity (server)' ~ Channel is unrecoverably broken and will be disposed!
09-13 17:12:10.066  1909  4255 W InputDispatcher: Attempted to unregister already unregistered input channel 'df8e368 com.jagex.oldscape.android/com.jagex.android.MainActivity (server)'
09-13 17:12:10.115  1747  1747 E lowmemorykiller: Error opening /proc/3493/oom_score_adj; errno=2
09-13 17:12:10.144  1909  4062 I ActivityManager: Process com.jagex.oldscape.android (pid 3493) has died: vis  +99TOP 
09-13 17:12:10.144  1909  1927 W libprocessgroup: kill(-3493, 9) failed: No such process
09-13 17:12:10.144  1909  1927 I libprocessgroup: Successfully killed process cgroup uid 10083 pid 3493 in 0ms
09-13 17:12:10.209  1749  2440 W SurfaceFlinger: Attempting to set client state on removed layer: com.jagex.oldscape.android/com.jagex.android.MainActivity#0
09-13 17:12:10.226  1909  1925 W Looper  : Slow dispatch took 111ms android.ui h=com.android.server.am.ActivityManagerService$UiHandler c=null m=31
09-13 17:12:10.226  1909  1932 W ActivityManager: setHasOverlayUi called on unknown pid: 3493
09-13 17:12:10.226  1909  3564 I ActivityManager: Killing 2781:com.location.provider/u0a47 (adj 904): empty #17
09-13 17:12:10.230  1909  1927 W libprocessgroup: kill(-2781, 9) failed: No such process
09-13 17:12:10.276  1909  1927 W libprocessgroup: kill(-2781, 9) failed: No such process
09-13 17:12:10.278  1731  1731 I Zygote  : Process 2781 exited due to signal (9)
09-13 17:12:10.287  1909  1941 I HCALL   : hcallOnActivityDisplayedRpc(com.bluestacks.launcher, com.bluestacks.launcher.activity.HomeActivity, com.bluestacks.launcher)
09-13 17:12:10.287  1909  1941 I VMSG    : getHostBoundBuffer:94 called for hcal
09-13 17:12:10.287  1909  1941 I VMSG    : processRequest:104 called for hcal
09-13 17:12:10.288  1909  1941 I HCALL   : hcallSetAppConfigDbParamsRpc(com.bluestacks.launcher, 0, 0, , 0)
09-13 17:12:10.288  1909  1941 I VMSG    : getHostBoundBuffer:94 called for hcal
09-13 17:12:10.288  1909  1941 I VMSG    : processRequest:104 called for hcal
09-13 17:12:10.300  1749  2440 I chatty  : uid=1000(system) Binder:1749_4 identical 1 line
09-13 17:12:10.316  1909  1927 W libprocessgroup: kill(-2781, 9) failed: No such process
09-13 17:12:10.316  1909  1927 I libprocessgroup: Successfully killed process cgroup uid 10047 pid 2781 in 86ms
09-13 17:12:10.317  2623  2693 E EGL_emulation: tid 2693: eglSurfaceAttrib(1378): error 0x3009 (EGL_BAD_MATCH)
09-13 17:12:10.317  2623  2693 W OpenGLRenderer: Failed to set EGL_SWAP_BEHAVIOR on surface 0x7c63c2334280, error=EGL_BAD_MATCH
09-13 17:12:10.913  1762  1851 E storaged: getDiskStats failed with result NOT_SUPPORTED and size 0
09-13 17:12:11.141  1745  1745 E adbd    : failed to connect to socket 'tcp:61666': Connection refused
09-13 17:12:12.693  1745  1745 E adbd    : failed to connect to socket 'tcp:61666': Connection refused
09-13 17:12:15.209  3131  3140 W System  : A resource failed to call end. 
09-13 17:12:15.209  3131  3140 I chatty  : uid=10011(com.android.vending) FinalizerDaemon identical 2 lines
09-13 17:12:15.209  3131  3140 W System  : A resource failed to call end. 
09-13 17:12:15.261  1745  1745 E adbd    : failed to connect to socket 'tcp:61666': Connection refused
09-13 17:12:19.708  1745  1745 E adbd    : failed to connect to socket 'tcp:61666': Connection refused
09-13 17:12:20.109  2287  2380 I VMSG    : processRequest:104 called for gcal
09-13 17:12:20.109  2287  2383 I BstGCallService-JNI: gcallSetClipboardTextClbk called
```

**Emulator or device (please complete the following information):**
 - Device/Emulator: BS
 - OS: P64
 - Arch: ARM

**Comment by iDznPB** [comment]
resolved with todays update
