### ISSUE TITLE
[BUG] Crash when saving GUI profile

### ISSUE THREAD

**Issue by Krulvis** [powbot/issues#86]
**Describe the bug**
Client crashes when saving a GUI profile (krul Combiner)

**To Reproduce/Line of code causing issue**
Create and save a profile for krul Combiner

**Logs**
```
09-18 00:00:15.106 12471 12471 E AndroidRuntime: FATAL EXCEPTION: main
09-18 00:00:15.106 12471 12471 E AndroidRuntime: Process: com.jagex.oldscape.android, PID: 12471
09-18 00:00:15.106 12471 12471 E AndroidRuntime: io.grpc.StatusRuntimeException: UNAVAILABLE: HTTP status code 502
09-18 00:00:15.106 12471 12471 E AndroidRuntime: invalid content-type: text/html
09-18 00:00:15.106 12471 12471 E AndroidRuntime: headers: Metadata(:status=502,date=Sat, 17 Sep 2022 22:00:14 GMT,content-type=text/html,cf-cache-status=DYNAMIC,report-to={"endpoints":[{"url":"https:\/\/a.nel.cloudflare.com\/report\/v3?s=x9UL81t%2B7iasXu6Fj7uSl7cNeJJEmDuh0ALwte03YZyXuURBdF4GslXUD%2Bn7%2Fm6n1X0SeVll6TJESSu99bt46RtA%2BGRX9CBLRbbTXgIXYf91Zq%2BKZoEH2vN7VrX0pyxWvOwsChSI"}],"group":"cf-nel","max_age":604800},nel={"success_fraction":0,"report_to":"cf-nel","max_age":604800},server=cloudflare,cf-ray=74c51d143b7c0b63-AMS,alt-svc=h3=":443"; ma=86400, h3-29=":443"; ma=86400)
09-18 00:00:15.106 12471 12471 E AndroidRuntime: DATA-----------------------------
09-18 00:00:15.106 12471 12471 E AndroidRuntime: <html>
09-18 00:00:15.106 12471 12471 E AndroidRuntime: <head><title>502 Bad Gateway</title></head>
09-18 00:00:15.106 12471 12471 E AndroidRuntime: <body>
09-18 00:00:15.106 12471 12471 E AndroidRuntime: <center><h1>502 Bad Gateway</h1></center>
09-18 00:00:15.106 12471 12471 E AndroidRuntime: <hr><center>openresty</center>
09-18 00:00:15.106 12471 12471 E AndroidRuntime: </body>
09-18 00:00:15.106 12471 12471 E AndroidRuntime: </html>
09-18 00:00:15.106 12471 12471 E AndroidRuntime: 
09-18 00:00:15.106 12471 12471 E AndroidRuntime: DATA-----------------------------
09-18 00:00:15.106 12471 12471 E AndroidRuntime: 
09-18 00:00:15.106 12471 12471 E AndroidRuntime:        at io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:271)
09-18 00:00:15.106 12471 12471 E AndroidRuntime:        at io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:252)
09-18 00:00:15.106 12471 12471 E AndroidRuntime:        at io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:165)
09-18 00:00:15.106 12471 12471 E AndroidRuntime:        at org.powbot.proto.script.ProfileServiceGrpc$ProfileServiceBlockingStub.storeProfile(ProfileServiceGrpc.java:319)
09-18 00:00:15.106 12471 12471 E AndroidRuntime:        at org.powbot.mobile.service.ScriptProfileService.storeProfile(ScriptProfileService.kt:28)
09-18 00:00:15.106 12471 12471 E AndroidRuntime:        at org.powbot.mobile.service.ScriptProfileService.storeProfile$default(ScriptProfileService.kt:22)
09-18 00:00:15.106 12471 12471 E AndroidRuntime:        at org.powbot.mobile.ui.modal.ScriptProfile.case(ScriptProfile.kt:277)
09-18 00:00:15.106 12471 12471 E AndroidRuntime:        at org.powbot.mobile.ui.modal.ScriptProfile.long(ScriptProfile.kt:102)
09-18 00:00:15.106 12471 12471 E AndroidRuntime:        at org.powbot.mobile.ui.modal.ScriptProfile.case(ScriptProfile.kt:87)
09-18 00:00:15.106 12471 12471 E AndroidRuntime:        at org.powbot.mobile.ui.modal.ScriptProfile.lambda$dop6rXSrgBpdGUEGLPBOHJ9VRy4(Unknown Source:0)
09-18 00:00:15.106 12471 12471 E AndroidRuntime:        at org.powbot.mobile.ui.modal.-$$Lambda$ScriptProfile$dop6rXSrgBpdGUEGLPBOHJ9VRy4.onClick(Unknown Source:2)
09-18 00:00:15.106 12471 12471 E AndroidRuntime:        at android.view.View.performClick(View.java:7520)
09-18 00:00:15.106 12471 12471 E AndroidRuntime:        at android.view.View.performClickInternal(View.java:7489)
09-18 00:00:15.106 12471 12471 E AndroidRuntime:        at android.view.View.access$3600(View.java:826)
09-18 00:00:15.106 12471 12471 E AndroidRuntime:        at android.view.View$PerformClick.run(View.java:28555)
09-18 00:00:15.106 12471 12471 E AndroidRuntime:        at android.os.Handler.handleCallback(Handler.java:938)
09-18 00:00:15.106 12471 12471 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:99)
09-18 00:00:15.106 12471 12471 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:233)
09-18 00:00:15.106 12471 12471 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:8063)
09-18 00:00:15.106 12471 12471 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
09-18 00:00:15.106 12471 12471 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:631)
09-18 00:00:15.106 12471 12471 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:978)

```

**Emulator or device (please complete the following information):**
 - Device/Emulator: OnePlus 5G N10
 - OS: LineageOS
 - Arch: arm64-v8a

**Comment by constt** [comment]
@Krulvis looks like API was down at that time?

Please try now
